# Numpy Library 

In [1]:
print("Hello world")

Hello world


In [2]:
import numpy as np

In [3]:
myarray = np.array([[1,2,3,4,5]], np.int8)

In [4]:
myarray

array([[1, 2, 3, 4, 5]], dtype=int8)

In [5]:
myarray.shape

(1, 5)

In [6]:
myarray.size

5

In [7]:
myarray.dtype

dtype('int8')

In [8]:
myarray[0,2] = 45

https://numpy.org/doc/1.20/user/basics.creation.html
There are 5 general mechanisms for creating arrays:

Conversion from other Python structures (e.g., lists, tuples)

Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)

Reading arrays from disk, either from standard or custom formats

Creating arrays from raw bytes through the use of strings or buffers

Use of special library functions (e.g., random)

In [9]:
py_ar = [2,4,6]

In [10]:
py_ar

[2, 4, 6]

In [16]:
from timeit import default_timer as timer

a = np.random.randn(1000)
b = np.random.randn(1000)
A = list(a)
B = list(b)

T = 1000

def dot1():
    dot = 0
    for i in range(len(A)):
        dot += A[i] * B[i]
    return dot

def dot2():
    return np.dot(a,b)

start = timer()
for i in range(T):
    dot1()
end = timer()
t1 = end - start

start = timer()
for i in range(T):
    dot2()
end = timer()
t2 = end - start

print("timer of list is ", t2)
print("timer of numpy array is ", t1)
print("ratio of them is ", t1/t2)

timer of list is  0.0027830000035464764
timer of numpy array is  0.39046450005844235
ratio of them is  140.30344935711804


In [23]:
a = np.array([[1,2,3],[4,5,6]])
print(a, "\n")
print(a.size, "\n")
print(a.shape, "\n")
print(a.T)


[[1 2 3]
 [4 5 6]] 

6 

(2, 3) 

[[1 4]
 [2 5]
 [3 6]]


In [35]:
print(a[:,0], "\n")
print(a[0,:])

[1 4] 

[1 2 3]


In [34]:
print(a[-1,-2])

5


# ***Getting inverse, determinant and diagonal matrix of nD array***

In [33]:
b = np.array([[2,1,3], [0,-1,4], [-2,3,1]])
print("inverse is \n", np.linalg.inv(b), "\n")
print("determinant is \n", np.linalg.det(b), "\n")
print("diagonal elements are \n", np.diag(b), "\n")

c = np.diag(b)
print("diagonal matrix is \n", np.diag(c))

inverse is 
 [[ 0.325 -0.2   -0.175]
 [ 0.2   -0.2    0.2  ]
 [ 0.05   0.2    0.05 ]] 

determinant is 
 -39.99999999999998 

diagonal elements are 
 [ 2 -1  1] 

diagonal matrix is 
 [[ 2  0  0]
 [ 0 -1  0]
 [ 0  0  1]]


# Boolean indexing

In [41]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [44]:
bool_idx = a>2
# here a is the name of same matrix
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [49]:
print(a[bool_idx], "\n")
print(a[a>2])
#both can be used and work similar

[3 4 5 6] 

[3 4 5 6]


In [53]:
b = np.where(a>2, a, 999)
#third argument is the desired value we want to fill where element is not according to condition
print(b)

[[999 999]
 [  3   4]
 [  5   6]]


In [54]:
# Fancy indexing
a = np.array([10,20,30,40,50,60])
l = [1,3,5]
print(a[l])

[20 40 60]


In [57]:
a = np.array([10, 33, 67, 78, 89, 44, 12])
even = np.argwhere(a%2 == 0).flatten()
print(a[even])


[10 78 44 12]


In [59]:
a= np.arange(1,11)
print(a, "\n")
print(a.shape, "\n")
#reshaping the array
b = a.reshape(2,5)
print(b)

[ 1  2  3  4  5  6  7  8  9 10] 

(10,) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [63]:
#using new axis method
a = np.arange(1,7)
c = a[np.newaxis, :]
print(c.shape, "\n")
print(c, "\n")

d = a[:, np.newaxis]
print(d.shape, "\n")
print(d)


(1, 6) 

[[1 2 3 4 5 6]] 

(6, 1) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# Concatenation in array

In [80]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
c = np.concatenate((a,b), axis=0)
d = np.concatenate((a,b), axis=None)
print(c, "\n and\n", d)

[[1 2]
 [3 4]
 [5 6]] 
 and
 [1 2 3 4 5 6]


In [81]:
e = np.concatenate((a,b.T), axis=1)
#if we take the b in initial form(without transpose) then it will throw value error.
print(e)

[[1 2 5]
 [3 4 6]]


In [77]:
# hstack and vstack methods
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.hstack((a,b))
d = np.vstack((a,b))

print(c, "\n")
print(d)

[1 2 3 4 5 6 7 8] 

[[1 2 3 4]
 [5 6 7 8]]


# Broadcasting

In [78]:
a = np.array([[1,2,3], [4,5,6], [1,2,3], [4,5,6]])
b = np.array([[1,0,1]])
c = a + b
print(c)
# In this type of addition each element of respective index are added to their corresponding element from second aarray

[[2 2 4]
 [5 5 7]
 [2 2 4]
 [5 5 7]]


# Functions

In [93]:
a = np.array([[12,13,14,15,16,17], [15,16,17,18,19,20]])
print("Sum of elements is ", a.sum())
print("Sum of elements at axis 0 is ", a.sum(axis=0))
print("Sum of elements at axis 1 is ", a.sum(axis=1))
print("Mean of elements is ", a.mean())
print("Variance is", a.var())
print("Standard deviatoin is ", a.std())

# We can also write:
# print(np.mean(a, axis=None))

Sum of elements is  192
Sum of elements at axis 0 is  [27 29 31 33 35 37]
Sum of elements at axis 1 is  [ 87 105]
Mean of elements is  16.0
Variance is 5.166666666666667
Standard deviatoin is  2.273030282830976


# Datatypes

In [99]:
x = np.array([1.0 , 2.0], dtype = np.float64)
print(x.dtype)

float64


# Copying vs reference

In [104]:
# int the following example we used the same refernece thats why both variables got updated 
a = np.array([1,2,3,4])
b = a
b[0] = 45
print("b is ", b)
print("a is ", a)

b is  [45  2  3  4]
a is  [45  2  3  4]


In [106]:
a = np.array([1,2,3,4])
b = a.copy()
# Using the copy function to safely copy
b[0] = 45
print("b is ",b)
print("a is ",a)

b is  [45  2  3  4]
a is  [1 2 3 4]


# Generating random arrays

In [116]:
a = np.zeros((3,3))
print(a)
print(a.dtype, "\n")
b = np.ones((2,3))
print(b, "\n")
c = np.full((2,3), 99)
print(c, "\n")
d = np.eye(4)
print(d, "\n")
e = np.arange(8)
print(e, "\n")
f = np.linspace(0,3,10)
print(f)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[99 99 99]
 [99 99 99]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[0 1 2 3 4 5 6 7] 

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


In [126]:
a = np.random.random((3,2))
print(a, "\n") # mean =0 and var=1 and gives no's in bw. 0-1

a = np.random.randn(2,3) # normal/Gaussian distribution 
print(a, "\n")
print(a.mean(), a.var())

a = np.random.randn(25) # normal/Gaussian distribution 
print(a, "\n")
print(a.mean(), a.var(), "\n")

a = np.random.randint(2,10, size=(3,3)) #using only one number then 0 will be lower bound
print(a, "\n")

a = np.random.choice(5, size=8)
print(a, "\n")

a = np.random.choice([1,2,3,4], size=8)
print(a, "\n")

[[0.6120766  0.48941934]
 [0.07812656 0.67151188]
 [0.90550451 0.70507299]] 

[[ 0.08275811 -0.17620627 -0.16361797]
 [ 0.33893139  0.08923664  1.12026015]] 

0.21522700955621119 0.1940921460704336
[-0.9032947  -0.09255086 -0.13259117 -1.19470757 -0.18195837 -0.60562263
 -1.17320255  1.00709591 -1.86110923 -0.7244434  -0.31235903 -1.52543618
  0.70767122  1.62262148  0.70843045 -0.02434074  0.855517   -1.65268218
 -1.65157109  0.46643857  0.50334306  1.9969364   1.17758665  0.06769581
  0.67769653] 

-0.08979346578524652 1.0963122069416538 

[[4 6 2]
 [6 8 7]
 [3 4 5]] 

[1 0 3 1 4 3 2 4] 

[4 2 3 4 2 2 4 1] 



# Linear Algebra

In [133]:
a = np.array([[1,2],[3,4]])
eigenValues, eigenVectors = np.linalg.eig(a)
print("Eigen values are \n", eigenValues)
print("Eigen vectors are \n ", eigenVectors) #column vector

Eigen values are 
 [-0.37228132  5.37228132]
Eigen vectors are 
  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [138]:
# For verification we know that :
# e_vec * e_val = A * e_vec

b = eigenVectors[:,0] * eigenValues[0]
c = a @ eigenVectors[:,0]

#print(b==c) will give wrong 
print(np.allclose(b,c))

True


* Q1. The admission fees of a small fair is 1.5 for children and 4.0 for adults.on a certain day 2200 people visited the fair and 5050 was collected. How many children and adults attended the fair? *

Solution:
x1 + x2 = 2200
(1.5)x1 + (4.0)x2 = 5050

Ax = b
=> x = inv(A)*b

In [142]:
A = np.array([[1,1], [1.5, 4.0]])
b = np.array([2200, 5050])
x = np.linalg.inv(A).dot(b)
print(x)

x = np.linalg.solve(A,b)
print(x)

[1500.  700.]
[1500.  700.]


# Loading .csv files 

In [145]:
# np.loadtxt or np.genfromtxt

# data = np.loadtxt("fileName.csv", delimeter=",", dtype=np.float32)
#print(data)